name:                hremote-android-tv
version:             0.1.0.0
github:              "tulth/hremote-android-tv"
license:             BSD3
author:              "tulth"
maintainer:          "example@example.com"
copyright:           "2022 Tulth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hremote-android-tv#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- typed-process
- directory
- servant-server
- warp
- wai
- wai-logger
- wai-extra
- wai-cors
- bytestring
- transformers
- mtl
- http-conduit
- http-media
- aeson
- containers
- text
- extra
- bytestring
- servant-blaze
- blaze-html

ghc-options:
- -Wall
- -Wcompat
- -Wcpp-undef
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-imports
- -Wunused-local-binds
# - -Werror

library:
  source-dirs: src

executables:
  hremote-android-tv-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hremote-android-tv
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hremote-android-tv-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hremote-android-tv
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
